services:
  flask-app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: flask-app
    image: nickosipov/flask-app:latest
    ports:
      - "5000:5000"
    env_file:
      - .env
    depends_on:
      - clickhouse

  # mysql-db:
  #   image: mysql:5.7
  #   container_name: mysql-db
  #   env_file:
  #     - .env
  #   ports:
  #     - "3306:3306"
  #   volumes:
  #     - mysql-db-data:/var/lib/mysql
  #     - ./migrations/init.sql:/docker-entrypoint-initdb.d/init.sql

  clickhouse:
    image: clickhouse/clickhouse-server:latest
    container_name: clickhouse
    environment:
      - CLICKHOUSE_DB=default
      - CLICKHOUSE_USER=default
      - CLICKHOUSE_PASSWORD=password
      - CLICKHOUSE_DEFAULT_ACCESS_MANAGEMENT=1
    ports:
      - 8123:8123 # http
      - 9000:9000 # tcp
    volumes:
      - clickhouse_data:/var/lib/clickhouse
      - ./migrations/ch-init.sql:/docker-entrypoint-initdb.d/ch-init.sql

volumes:
  mysql-db-data:
  clickhouse_data:
