FROM python:3.11.4-slim-bookworm

WORKDIR /app

RUN pip install notebook

COPY notebooks notebooks

CMD ["jupyter", "notebook", "--ip=0.0.0.0", "--port=8888", "--no-browser", "--allow-root", "--NotebookApp.token=''", "--NotebookApp.password=''"]